name: Go

on:
  - push
  - pull_request

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: make build

    - name: Test
      run: go test -v ./...

    - name: Upload a Build Artifact ARM64
      uses: actions/upload-artifact@v2.2.2
      with:
        name: artifacts.zip
        path: ./bin/waypoint-plugin-consul-release-controller_linux_arm64.zip

    - name: Upload a Build Artifact AMD64
      uses: actions/upload-artifact@v2.2.2
      with:
        name: artifacts.zip
        path: ./bin/waypoint-plugin-consul-release-controller_linux_amd64.zip
